### PR TITLE
feat: add "raw" module option for binary files

### PR DESCRIPTION
**Pull request by rassie**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

I've tried loading a PDF into a variable only to find out that the loaded content is converted to a UTF-8 string, which corrupts the PDF. Since `module.exports.raw` is not set, this is actually documented behaviour, however the expectation is for something called `raw-loader` to be as raw as it gets. This new option replicates [Webpack's string conversion](https://github.com/webpack/webpack/blob/f06086c53b2277e421604c5cea6f32f5c5b6d117/lib/NormalModule.js#L109) for non-raw loads (default) and skips it on raw ones. 

### Breaking Changes

Should be backwards-compatible.

### CODE REVIEW

**Comment by rassie** [comment]
I'm sorry, I've tried a couple of things and I have no idea how to make tests work on both Linux and Windows without Jest thinking there are obsolete snapshots. Any idea how to fix this?

**Comment by rassie** [comment]
@evilebottnawi sorry to bother you, but could you review this PR?

**Comment by evilebottnawi** [comment]
@rassie Why do you use raw-loader for loading pdf? Can you provide real use case example?

**Comment by rassie** [comment]
In our product we are working with customer-uploaded PDFs. In some pre-defined cases, there is no PDF that the customer can upload (yet), in which case we upload a small dummy PDF instead (about 1k) to keep the backend API sane and let algorithms work correctly. To upload this dummy, we need its contents in frontend code as `File`, which we could either fetch via an additional `fetch()` to `/static/dummy.pdf` or just inline it with `raw-loader`. The latter is way faster and simpler.

I hope this case is real enough :) I can also imagine a use-case with public encryption certificates being inlined for some kind of secure communication, but that's not a use-case we have.

**Comment by evilebottnawi** [comment]
@rassie We don't need option for it, ideally loader should work out of box without options, maybe you can provide part of file where problem(s) happens (for tests)?

**Comment by rassie** [comment]
> @rassie I think you don't need `raw-loader`, `raw-loader` only inject file to code without any transformations, I think you need https://github.com/webpack-contrib/val-loader here

I think you are missing the bigger point here: neither `raw-loader` nor `val-loader` set the [`raw` flag](https://webpack.js.org/api/loaders/#raw-loader), which is necessary to pass loaded content as-is without transformation. Default on missing flag is to transform to UTF-8, which is what `raw-loader` currently doing. It's impossible to introduce the flag without breaking the backward compatibility, this is why I tried introducing an option.

**Comment by evilebottnawi** [comment]
> I think you are missing the bigger point here: neither raw-loader nor val-loader set the raw flag, which is necessary to pass loaded content as-is without transformation. 

Because it is unnecessary, raw-loader **should not transform**, if you need it you can using `val-loader`/create own loader. As I said above it is out of scope `raw-loader`.

> Default on missing flag is to transform to UTF-8, which is what raw-loader currently doing.

It is wrong, we don't know really how developers will load raw content.

>  It's impossible to introduce the flag without breaking the backward compatibility, this is why I tried introducing an option.

Because we don't need this option.

For webpack@5 this loader will be defaults in favor built-in ability `asset/source` module type - https://webpack.js.org/guides/asset-modules/. So we don't accept features, only fixes.

**Comment by rassie** [comment]
I'm sorry, I think I fail to understand your point fully, but I also think we are talking about different things. I'd appreciate if you'd bear with me for a bit longer, I want to understand the issue fully since that defines way forward for my problem, with `raw-loader` or without it.

> Because it is unnecessary, raw-loader **should not transform**, if you need it you can using `val-loader`/create own loader. As I said above it is out of scope `raw-loader`.

If you are saying that `raw-loader` is not transforming any content it receives you are technically correct, since the transformation is applied to the content by `webpack`, but is based on the flag set or unset in `raw-loader` source code. However, the notion "`raw-loader` is loading files bit for bit exactly as they are on the disk" is what I initially thought about `raw-loader`, but that's not the behaviour I'm observing. 

I've added a couple of tests on binary files to this PR (we can remove them later), maybe we can reach understanding this way. In these tests, a binary file with an MD5 hash of `394e219db24b8dfb02b7db40543c81f2` is being loaded twice, once with default `raw-loader` configuration and once again with the `raw` option. MD5 hash is wrong in the first case and correct in the second. 

> > Default on missing flag is to transform to UTF-8, which is what raw-loader currently doing.

> It is wrong, we don't know really how developers will load raw content.

I think I misspoke: this is what `webpack` is doing before giving the content to `raw-loader`. `raw-loader` does not do anything to the content, but the effect for the developer is the same: text files in ASCII or UTF-8 are unchanged, everything else is transcoded by `webpack`. This is literally [documented behaviour](https://webpack.js.org/api/loaders/#raw-loader).

**Comment by evilebottnawi** [comment]
> I've added a couple of tests on binary files to this PR (we can remove them later), maybe we can reach understanding this way. In these tests, a binary file with an MD5 hash of 394e219db24b8dfb02b7db40543c81f2 is being loaded twice, once with default raw-loader configuration and once again with the raw option. MD5 hash is wrong in the first case and correct in the second.

Yes, because:
- without utf-8 it is binary
- with utf-8 it is not binary

I still can not understand what is your problem.

Actually the `raw` option breaks cases when developer want to load files non UTF-8 files. Confuse for develpers. And performs invalid transformation. We do not know how developer will load asset module.

**Comment by rassie** [comment]
Yet again, I'm sorry I'm unable to explain my problem more coherently, it's entirely possible I misunderstand how `raw-loader` is supposed to work. Could we try another thought experiment?

There is a `file.txt` in the `tests/fixtures` directory, encoded as UTF-8, containing Nekrosov's quote in Russian and English. If we convert that file to CP1251 and then load it via `raw-loader` to a variable `txt`, what content is this variable expected to have?

1. a CP1251-encoded string which, when converted to UTF-8, would contain Nekrasov's quote in both languages
2. a UTF-8-encoded string with Nekrasov's quote in both languages
3. a binary string containing gibberish (which is actually CP1251 interpreted as UTF-8) in place of the Russian quote and Nekrasov's quote in English 
4. something else entirely

My expectation is number 1, what I'm actually seeing is 3. That's my whole problem I'm trying to solve.

**Comment by evilebottnawi** [comment]
> a binary string containing gibberish (which is actually CP1251 interpreted as UTF-8) in place of the Russian quote and Nekrasov's quote in English

Where is `gibberish`? 

**index.js**

```js
import txt from 'raw-loader!./file.txt';

console.log(Array.from(txt).map(c => c.charCodeAt(0)));
```

**file.txt**

```
Собака Dog
```

Output:
```
(12) [65533, 65533, 65533, 65533, 65533, 65533, 32, 100, 111, 103, 32, 65533]
```

With you changes output is same.

**Comment by evilebottnawi** [comment]
When you use `raw` on loader, `webpack` convert buffer to `string` using `toString()` (https://github.com/webpack/loader-runner/blob/c55de2c1e5857830208cd1122c45f7d13d260988/lib/LoaderRunner.js#L152), so adding `source.toString('utf-8')` just doesn't have sense, webpack already do it

**Comment by rassie** [comment]
> **file.txt**
> 
> ```
> Собака Dog
> ```
> 
> Output:
> 
> ```
> (10) [65533, 65533, 65533, 65533, 65533, 65533, 32, 68, 111, 103]
> ```
> 
> With you changes output is same.

You are confusing me once again. Your code shows that "Собака" has been loaded as six replacement characters (Unicode 0x65533), which is exactly what I'm talking about: it's broken and produces unrecoverable gibberish. What am I missing?

**Comment by evilebottnawi** [comment]
@rassie Your solution do same :smile: Maybe you can provide example with pdf?

**Comment by rassie** [comment]
> When you use `raw` on loader, `webpack` convert buffer to `string` using `Buffer.from()` (https://github.com/webpack/loader-runner/blob/c55de2c1e5857830208cd1122c45f7d13d260988/lib/LoaderRunner.js#L152), so adding `source.toString('utf-8')` just doesn't have sense, webpack already do it

You are linking to code which converts from a `string` to a `Buffer` (see the guarding `if` above). `source.toString('utf-8')` does the opposite, which is guarded by `Buffer.isBuffer()`.

**Comment by rassie** [comment]
> @rassie Your solution do same  Maybe you can provide example with pdf?

That might be true, let me check that. But do you see the original issue now, `raw-loader` without `raw` flag outputting corrupted binaries?

**Comment by evilebottnawi** [comment]
@rassie 

> You are linking to code which converts from a string to a Buffer (see the guarding if above). source.toString('utf-8') does the opposite, which is guarded by Buffer.isBuffer().

No need it

> That might be true, let me check that. But do you see the original issue now, raw-loader without raw flag outputting corrupted binaries?

It is convert it to `utf8`

**Comment by rassie** [comment]
> > @rassie Your solution do same  Maybe you can provide example with pdf?
> 
> That might be true, let me check that. But do you see the original issue now, `raw-loader` without `raw` flag outputting corrupted binaries?

Checked that. You are right, but also wrong :) The key is that the `raw` flag returns a `Buffer` which is needed for binary processing. So if I convert the `Buffer` I received to UTF-8 I'm getting the same result. Which is completely logical, since converting to UTF-8 is what I actually want to avoid and can't since `raw-loader` is not setting the `raw` flag.

**Comment by rassie** [comment]
> @rassie Your solution do same  Maybe you can provide example with pdf?

PDF test is essentially the same one as binary test, but here you go, I've pushed a commit containing such a test. Problem stays the same: MD5 checksum is incorrect for default behaviour and correct with `raw` option.

**Comment by evilebottnawi** [comment]
@rassie you can't use non utf8 characters in your bundle, you should convert them before using

**Comment by rassie** [comment]
I don't think I do. `Buffer`'s JSON representation is ASCII, so there shouldn't be a problem with that.

**Comment by evilebottnawi** [comment]
I still can't understand a problem, all that you do is expected behavior and works as expected, if you need magic, you can create own loader

**Comment by evilebottnawi** [comment]
`toString('utf8')` is not covert `windiws-1251` to `utf8`

**Comment by rassie** [comment]
> I still can't understand a problem, all that you do is expected behavior and works as expected, if you need magic, you can create own loader

I probably just need a `Buffer`, not a UTF-8 string. Another loader would mostly be just a copy of `raw-loader`. But if I understand correctly, I'd need a new loader for Webpack 5 anyway, since `asset/source` can't output a `Buffer` anymore.

**Comment by evilebottnawi** [comment]
> I probably just need a Buffer, not a UTF-8 string. Another loader would mostly be just a copy of raw-loader. But if I understand correctly, I'd need a new loader for Webpack 5 anyway, since asset/source can't output a Buffer anymore.

And do should do it, it is out of scope of this module type

**Comment by evilebottnawi** [comment]
As I said above:

> you can't use non utf8 characters in your bundle, you should convert them before using

Please covert file to `utf8` before build, you can achieve it using difference ways

**Comment by evilebottnawi** [comment]
From node docs:

> If encoding is 'utf8' and a byte sequence in the input is not valid UTF-8, then each invalid byte is replaced with the replacement character U+FFFD.

**Comment by rassie** [comment]
> As I said above:
> 
> > you can't use non utf8 characters in your bundle, you should convert them before using
> 
> Please covert file to `utf8` before build, you can achieve it using difference ways

Which file(s) are you talking about?

**Comment by evilebottnawi** [comment]
@rassie contains non utf8 characters

**Comment by rassie** [comment]
> If encoding is 'utf8' and a byte sequence in the input is not valid UTF-8, then each invalid byte is replaced with the replacement character U+FFFD.

Do you have link for me on that? Somehow, googling this quote does not give any results.

**Comment by rassie** [comment]
Found it. https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end

**Comment by evilebottnawi** [comment]
@rassie So we can close?

**Comment by rassie** [comment]
I guess so, I'm by no means closer to the proper solution, but a custom loader will have to do. Thanks for the patience.

**Pull request closed without merging**
